

# This file was *autogenerated* from the file database.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_10 = Integer(10)
load('tests.sage')
for k in range(_sage_const_5 ,_sage_const_10 ):
    print('k = ' + str(k))
    args = '-C ' + str(k)
    for G in graphs.nauty_geng(args):
        print(G)
        T = tau_test_convexity(G)
        print(T)
        if not T:
            print("G is not convex")
            print("vertices")
            print(G.vertices())
            print("edges")
            print(G.edges())

